### PR TITLE
Removed GA and replaced map with Leaflet

### PR DESCRIPTION
**Pull request by bahorn**
Still need to work out what we replace GA with, but this is much better for user privacy!

### CODE REVIEW

**Comment by bahorn** [comment]
Oh... can't use leaflet for server side rendering....

**Comment by jmsv** [comment]
looks like a great idea :+1:

sometimes SSR stuff works on the gatsby dev server but then falls over on productions builds 😢 I usually try and remember to run `npm run build` locally before committing when editing gatsby config

**Comment by bahorn** [comment]
yeah, i ended up finding a gatsby plugin that should handle it.

Had to directly import some of the leaflet stuff, which used `window` when it shouldn't have. Guide here https://www.gatsbyjs.org/packages/gatsby-plugin-react-leaflet/ worked.

And yeah, i'm going to start running gatsby build for committing  :) But it takes forever and I don't know why.

**Comment by bahorn** [comment]
It won't show the map in that deploy preview as I've only authorised the mapbox api key on covhack.org + my dev domain.

**Comment by bahorn** [comment]
Just authorised it for the domain.

still seem to be getting some 403s, but i guess that's just caching?

**Comment by jmsv** [comment]
might be worth adding `hacs.tech` too while we're still ALIASed or whatever from that :smile:

**Comment by bahorn** [comment]
Just added it!

**Comment by jmsv** [comment]
for some reason when I view the preview, it loads a few map tiles but 403s on others 🤔 looks good though! :tada:

**Comment by jmsv** [comment]
did you find a decent replacement analytics service?

**Comment by bahorn** [comment]
Still looking for one.

**Comment by bahorn** [comment]
What metrics to you want? Just number of people visiting + general idea of where they came from?

I don't see much value tracking mouse movements and stuff, so if it's just reading a referrer and increment an int, we can probably hack it up.

**Comment by jmsv** [comment]
yeah just really basic stuff like:

- how many hits the site gets
- referrers
- where did they come from
- where did they go
- where did they come from
- cotton eye joe

**Comment by bahorn** [comment]
So what I'm thinking for this more privacy preserving replacement:

Process on users web browser:
* Check if DNT is enabled, return if it is.
* Sample 10-20% of visits for further analysis
* Take the referer but only look at the domain, not the path.
* Pass this onto our function for logging.

Backend:
* Netlify function
* FaunaDB for storage due to it's integration with netlify

So with this, we make way less requests to the function and all we need to do is multiple the count by 5-10 times to get a fairly accurate estimate. I doubt we care for anything more than if people are coming from facebook, twitter or other social media.

**Comment by bahorn** [comment]
https://github.com/bahorn/privlytics

started work on the analytics system I described.

**Pull request closed without merging**
